version: "3"

services:
  contextlib-upload:
    # build: ./
    image: swnhieian/context-lib-upload
    ports:
      - "29000:80"
    volumes:
      - ./data:/flask/data
      - ./src:/flask/src
    deploy:
      restart_policy:
        condition: on-failure

  contextlib-fileBrowser:
    image: filebrowser/filebrowser
    volumes:
      - ./data:/srv
    ports:
      - "29001:80"
    deploy:
      restart_policy:
        condition: on-failure
